### PR TITLE
Add actual documentation link into calibration checker output

### PR DESCRIPTION
**Pull request by fmauch**
The output was generated when we didn't have the final repository available.
However, updating the output got lost over time...

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Would there be any way for us to track when this link breaks (ie: because you move sections around, move them to other files or rename the section)?

**Comment by fmauch** [comment]
I guess this would require a ci job that extracts the link from source code and checks it...

**Comment by gavanderhoorn** [comment]
MoveIt uses [html-proofer](https://github.com/gjtorikian/html-proofer) for this: [here](https://github.com/ros-planning/moveit_tutorials/blob/48f340e59ba1ced913ec4b2c8d5034c19ad2e0ae/.travis.yml#L50-L52).

Might be something to look into?

**Comment by fmauch** [comment]
I just used a simple bash script to achieve what I want.

Ideally we would let run this over the whole repository, but I found that we currently have a couple of invalid (as in 404) links in our codebase. I'll leave this for a separate PR, though.

**Comment by fmauch** [comment]
I'll merge this and add checking the other links separately.

**Comment by gavanderhoorn** [comment]
@fmauch: would it perhaps be better to add the `check_urls.sh` script to the `.github` directory?

`scripts` contains scripts used by users of the driver. The check url script seems out of place there.

**Comment by fmauch** [comment]
True. I'll keep that in mind when checking the other links, as well.

**Pull request merged**
