### PR TITLE
Adding link to the Survey for beta feedback

### PR DESCRIPTION
**Pull request by urrsk**
Now we are ready for the official beta release.
Ready, Set, Go testing!

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
The form links to the repository using an Outlook Safe Link, instead of the direct URL. Should that be fixed or was that done on purpose?

**Comment by urrsk** [comment]
> The form links to the repository using an Outlook Safe Link, instead of the direct URL. Should that be fixed or was that done on purpose?

Thanks for the comment
The link should be "https://share.hsforms.com/1_SsLjqMcT8SfaRUiYWwcrA1kep1" what link do you see?

**Comment by gavanderhoorn** [comment]
This link:

image

is not the plain link to `https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/beta-testing`, but:

> `https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUniversalRobots%2FUniversal_Robots_ROS_Driver%2Ftree%2Fbeta-testing&data=04%7C01%7C%7C9365042f370e4db42a2708d8e49c007c%7C311a22fd957640ab977ea2f0a4d2cd36%7C1%7C0%7C637510705991475598%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yMTpZsLwUydjnu1kuptBvfzKpWY55oxrzsAKbWNeOzw%3D&reserved=0`

**Comment by urrsk** [comment]
> This link:
> 
> image
> 
> is not the plain link to `https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/beta-testing`, but:
> 
> > `https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUniversalRobots%2FUniversal_Robots_ROS_Driver%2Ftree%2Fbeta-testing&data=04%7C01%7C%7C9365042f370e4db42a2708d8e49c007c%7C311a22fd957640ab977ea2f0a4d2cd36%7C1%7C0%7C637510705991475598%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yMTpZsLwUydjnu1kuptBvfzKpWY55oxrzsAKbWNeOzw%3D&reserved=0`



> This link:
> 
> image
> 
> is not the plain link to `https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/beta-testing`, but:
> 
> > `https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUniversalRobots%2FUniversal_Robots_ROS_Driver%2Ftree%2Fbeta-testing&data=04%7C01%7C%7C9365042f370e4db42a2708d8e49c007c%7C311a22fd957640ab977ea2f0a4d2cd36%7C1%7C0%7C637510705991475598%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yMTpZsLwUydjnu1kuptBvfzKpWY55oxrzsAKbWNeOzw%3D&reserved=0`

Ahh the link in the survey. Thanks for that comment. I will get it fixed.

**Comment by urrsk** [comment]
@gavanderhoorn The link is changed. Thanks for that comment

**Pull request merged**
