### PR TITLE
Use SPDX license identifiers

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

This reduces ambiguity and facilitates automated parsing and identification of licenses.

Refer to [spdx.org](https://spdx.org) for more information.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I'm not entirely sure whether all packages list all licenses correctly. I've not checked it.

**Comment by gavanderhoorn** [comment]
Closed->reopened to trigger Travis.

**Comment by gavanderhoorn** [comment]
Build has finished, but badges here are not reflecting it.

**Comment by fmauch** [comment]
CI running on travis-ci.org seems still not to be reporting back here. The build succeeded, however, so going to merge this.

**Pull request merged**
