### PR TITLE
Minor clarifications in the "auto-update calibration data" faq entry

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Apologies, I should have commented on #179.

**Comment by fmauch** [comment]
Thanks for coming back on this :-) I fully agree.

**Comment by gavanderhoorn** [comment]
@fmauch wrote:
> Thanks for coming back on this :-) I fully agree.

What, with this?

> Apologies, I should have commented on #179.

;)

**Comment by fmauch** [comment]
> @fmauch wrote:
> 
> > Thanks for coming back on this :-) I fully agree.
> 
> What, with this?
> 
> > Apologies, I should have commented on #179.
> 
> ;)

I meant the content ;-)

**Pull request merged**
